name: Playwright Tests

on:
  push:
    branches:
      - Master
  pull_request:
    branches:
      - Master
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Run Playwright tests (Chromium only)
        run: PW_BROWSER=chromium npx playwright test
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
